# Generated by Django 3.1.1 on 2021-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='categoryhero',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='categoryhero',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='categorynew',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='categorynew',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='value',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
    ]
