# Generated by Django 3.1.1 on 2021-04-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210416_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marked_price',
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(upload_to='static/img/heroes', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/img/items', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='static/img/news', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/img/products', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.PositiveIntegerField(verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(upload_to='static/img/ability', verbose_name='Hình ảnh'),
        ),
    ]
