# Generated by Django 3.1.1 on 2021-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210416_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Đã nhận', 'Đã nhận'), ('Đang xử lý', 'Đang xử lý'), ('Đang gửi', 'Đang gửi'), ('Hoàn thành', 'Hoàn thành'), ('Đã bị hủy', 'Đã bị hủy')], max_length=50, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
