# Generated by Django 3.1.1 on 2021-04-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210417_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đang gửi', 'Đang gửi'), ('Đã nhận', 'Đã nhận'), ('Hoàn thành', 'Hoàn thành'), ('Đã bị hủy', 'Đã bị hủy')], max_length=50, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
