# Generated by Django 3.1.1 on 2021-04-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210418_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Tổng tiền'),
        ),
    ]
