# Generated by Django 3.2.2 on 2021-05-18 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20210423_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='ngày viết')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người viết')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.new', verbose_name='Bình luận')),
            ],
        ),
    ]
